---
interface:
  agentic: True

vectorstore:
  score: 0.6
  max_objects: 10
  mode: "vector"
  embedding_dimensions: 3072
  query_mode: "default"
  collection: "default"
  provider: "inline-chromadb"
  chunk_size_in_tokens: 512
  embedding_timeout: 3600

openai:
  default_local_api: "http://localhost:8321"
  history_dir: "chat_histories"
  latest_history_filename: "latest_chat.json"
  model: "granite3.3:2b"
  embedding_model: "all-MiniLM-L6-v2"
  shield_model: "meta-llama/Llama-Guard-3-1b"
  api_key: "your_api_key"
  timeout: 120

features:
  enable_rag: False
  enable_shields: False

llm:
  temperature: 0.8
  top_p: 0.9
  max_tokens: 1024
  presence_penalty: 1.1
  repeat_penalty: 1.1
  n_comp: 1
  system_prompt: "You are an helpful assistant tasked to retrieve informations from a knowledge base. You must respond precisely and in no more than four senteces. If you cannot respond please tell that you do not know the answer. Use the following context to answer the question."
