version: '2'
image_name: llamachat-backend
apis:
- agents
- datasetio
- eval
- inference
- safety
- scoring
- telemetry
- tool_runtime
- vector_io
providers:
  inference:
  - provider_id: ollama-inference
    provider_type: remote::ollama
    config:
      url: ${env.INFERENCE_URL:=http://localhost:11434}
  - provider_id: ollama-safety
    provider_type: remote::ollama
    config:
      url: ${env.SAFETY_INFERENCE_URL:=http://localhost:11434}
  - provider_id: sentence-transformers
    provider_type: inline::sentence-transformers
    config: {}
  vector_io:
  - provider_id: chroma
    provider_type: inline::chromadb
    config:
      db_path: ${env.CHROMA_DB_PATH:=~/.llama/distributions/llamachat-backend}/chromadb.db
#      - provider_id: chromadb
#        provider_type: remote::chromadb
#        config:
#          url: ${env.CHROMA_DB_URL:=http://localhost:8080}
  safety:
  - provider_id: llama-guard
    provider_type: inline::llama-guard
    config:
      excluded_categories: []
  agents:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      persistence_store:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/llamachat-backend}/agents_store.db
      responses_store:
        type: sqlite
        db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/llamachat-backend}/responses_store.db
  eval:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/llamachat-backend}/meta_reference_eval.db
  datasetio:
  - provider_id: huggingface
    provider_type: remote::huggingface
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/llamachat-backend}/huggingface_datasetio.db
  - provider_id: localfs
    provider_type: inline::localfs
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/llamachat-backend}/localfs_datasetio.db
  scoring:
  - provider_id: basic
    provider_type: inline::basic
    config: {}
  - provider_id: llm-as-judge
    provider_type: inline::llm-as-judge
    config: {}
  telemetry:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      service_name: ${env.OTEL_SERVICE_NAME:=llama-stack}
      sinks: ${env.TELEMETRY_SINKS:=console,sqlite}
      otel_trace_endpoint: ${env.OTEL_TRACE_ENDPOINT:}
      sqlite_db_path: ${env.SQLITE_DB_PATH:=~/.llama/distributions/llamachat-backend/trace_store.db}
  tool_runtime:
  - provider_id: rag-runtime
    provider_type: inline::rag-runtime
    config: {}
  - provider_id: model-context-protocol
    provider_type: remote::model-context-protocol
    config: {}
metadata_store:
  type: sqlite
  db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/llamachat-backend}/registry.db
inference_store:
  type: sqlite
  db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/llamachat-backend}/inference_store.db
models:
- metadata: {}
  model_id: ${env.INFERENCE_MODEL:=granite3.3:2b}
  provider_id: ollama-inference
  model_type: llm
- metadata:
    embedding_dimension: 384
  model_id: ${env.EMBEDDING_MODEL:=all-MiniLM-L6-v2}
  provider_id: sentence-transformers
  model_type: embedding
- metadata: {}
  model_id: ${env.SAFETY_MODEL:=meta-llama/Llama-Guard-3-1B}
  provider_id: ollama-safety
  provider_model_id: ${env.SAFETY_MODEL_OLLAMA:=llama-guard3:1b}
  model_type: llm
shields:
- shield_id: ${env.SAFETY_MODEL:=meta-llama/Llama-Guard-3-1B}
vector_dbs: []
datasets: []
scoring_fns: []
benchmarks: []
tool_groups:
- toolgroup_id: builtin::rag
  provider_id: rag-runtime
server:
  port: 8321
